// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: stats.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseStatics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total      *BaseStatics_Total    `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	DetailList []*BaseStatics_Detail `protobuf:"bytes,2,rep,name=detail_list,json=detailList,proto3" json:"detail_list,omitempty"`
	ActionList []*BaseStatics_Action `protobuf:"bytes,3,rep,name=action_list,json=actionList,proto3" json:"action_list,omitempty"`
}

func (x *BaseStatics) Reset() {
	*x = BaseStatics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseStatics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseStatics) ProtoMessage() {}

func (x *BaseStatics) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseStatics.ProtoReflect.Descriptor instead.
func (*BaseStatics) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *BaseStatics) GetTotal() *BaseStatics_Total {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *BaseStatics) GetDetailList() []*BaseStatics_Detail {
	if x != nil {
		return x.DetailList
	}
	return nil
}

func (x *BaseStatics) GetActionList() []*BaseStatics_Action {
	if x != nil {
		return x.ActionList
	}
	return nil
}

type BasePushCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manufacturer string `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	DescribeTag  string `protobuf:"bytes,2,opt,name=describe_tag,json=describeTag,proto3" json:"describe_tag,omitempty"`
	TotalNum     int32  `protobuf:"varint,3,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	PushNum      int32  `protobuf:"varint,4,opt,name=push_num,json=pushNum,proto3" json:"push_num,omitempty"`
	RemainNum    int32  `protobuf:"varint,5,opt,name=remain_num,json=remainNum,proto3" json:"remain_num,omitempty"`
	HasLimit     bool   `protobuf:"varint,6,opt,name=has_limit,json=hasLimit,proto3" json:"has_limit,omitempty"`
}

func (x *BasePushCount) Reset() {
	*x = BasePushCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasePushCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasePushCount) ProtoMessage() {}

func (x *BasePushCount) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasePushCount.ProtoReflect.Descriptor instead.
func (*BasePushCount) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *BasePushCount) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *BasePushCount) GetDescribeTag() string {
	if x != nil {
		return x.DescribeTag
	}
	return ""
}

func (x *BasePushCount) GetTotalNum() int32 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *BasePushCount) GetPushNum() int32 {
	if x != nil {
		return x.PushNum
	}
	return 0
}

func (x *BasePushCount) GetRemainNum() int32 {
	if x != nil {
		return x.RemainNum
	}
	return 0
}

func (x *BasePushCount) GetHasLimit() bool {
	if x != nil {
		return x.HasLimit
	}
	return false
}

type GetTasksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushAgent string   `protobuf:"bytes,1,opt,name=push_agent,json=pushAgent,proto3" json:"push_agent,omitempty"`
	BundleId  string   `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	TaskList  []string `protobuf:"bytes,3,rep,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
}

func (x *GetTasksReq) Reset() {
	*x = GetTasksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksReq) ProtoMessage() {}

func (x *GetTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksReq.ProtoReflect.Descriptor instead.
func (*GetTasksReq) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetTasksReq) GetPushAgent() string {
	if x != nil {
		return x.PushAgent
	}
	return ""
}

func (x *GetTasksReq) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *GetTasksReq) GetTaskList() []string {
	if x != nil {
		return x.TaskList
	}
	return nil
}

type GetTasksResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskList    []string       `protobuf:"bytes,1,rep,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
	StaticsList []*BaseStatics `protobuf:"bytes,2,rep,name=statics_list,json=staticsList,proto3" json:"statics_list,omitempty"`
}

func (x *GetTasksResp) Reset() {
	*x = GetTasksResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResp) ProtoMessage() {}

func (x *GetTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResp.ProtoReflect.Descriptor instead.
func (*GetTasksResp) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksResp) GetTaskList() []string {
	if x != nil {
		return x.TaskList
	}
	return nil
}

func (x *GetTasksResp) GetStaticsList() []*BaseStatics {
	if x != nil {
		return x.StaticsList
	}
	return nil
}

type GetTaskGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushAgent string `protobuf:"bytes,1,opt,name=push_agent,json=pushAgent,proto3" json:"push_agent,omitempty"`
	BundleId  string `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Group     string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *GetTaskGroupReq) Reset() {
	*x = GetTaskGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskGroupReq) ProtoMessage() {}

func (x *GetTaskGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskGroupReq.ProtoReflect.Descriptor instead.
func (*GetTaskGroupReq) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskGroupReq) GetPushAgent() string {
	if x != nil {
		return x.PushAgent
	}
	return ""
}

func (x *GetTaskGroupReq) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *GetTaskGroupReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetTaskGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group   string       `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Statics *BaseStatics `protobuf:"bytes,2,opt,name=statics,proto3" json:"statics,omitempty"`
}

func (x *GetTaskGroupResp) Reset() {
	*x = GetTaskGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskGroupResp) ProtoMessage() {}

func (x *GetTaskGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskGroupResp.ProtoReflect.Descriptor instead.
func (*GetTaskGroupResp) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskGroupResp) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetTaskGroupResp) GetStatics() *BaseStatics {
	if x != nil {
		return x.Statics
	}
	return nil
}

type GetPushCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushAgent  string `protobuf:"bytes,1,opt,name=push_agent,json=pushAgent,proto3" json:"push_agent,omitempty"`
	BundleId   string `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	UnixSecond int64  `protobuf:"varint,3,opt,name=unix_second,json=unixSecond,proto3" json:"unix_second,omitempty"`
}

func (x *GetPushCountReq) Reset() {
	*x = GetPushCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPushCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushCountReq) ProtoMessage() {}

func (x *GetPushCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushCountReq.ProtoReflect.Descriptor instead.
func (*GetPushCountReq) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{6}
}

func (x *GetPushCountReq) GetPushAgent() string {
	if x != nil {
		return x.PushAgent
	}
	return ""
}

func (x *GetPushCountReq) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *GetPushCountReq) GetUnixSecond() int64 {
	if x != nil {
		return x.UnixSecond
	}
	return 0
}

type GetPushCountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountList []*BasePushCount `protobuf:"bytes,1,rep,name=count_list,json=countList,proto3" json:"count_list,omitempty"`
}

func (x *GetPushCountResp) Reset() {
	*x = GetPushCountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPushCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushCountResp) ProtoMessage() {}

func (x *GetPushCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushCountResp.ProtoReflect.Descriptor instead.
func (*GetPushCountResp) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{7}
}

func (x *GetPushCountResp) GetCountList() []*BasePushCount {
	if x != nil {
		return x.CountList
	}
	return nil
}

type GetPushDataByDayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushAgent  string `protobuf:"bytes,1,opt,name=push_agent,json=pushAgent,proto3" json:"push_agent,omitempty"`
	BundleId   string `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	UnixSecond int64  `protobuf:"varint,3,opt,name=unix_second,json=unixSecond,proto3" json:"unix_second,omitempty"`
}

func (x *GetPushDataByDayReq) Reset() {
	*x = GetPushDataByDayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPushDataByDayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushDataByDayReq) ProtoMessage() {}

func (x *GetPushDataByDayReq) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushDataByDayReq.ProtoReflect.Descriptor instead.
func (*GetPushDataByDayReq) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{8}
}

func (x *GetPushDataByDayReq) GetPushAgent() string {
	if x != nil {
		return x.PushAgent
	}
	return ""
}

func (x *GetPushDataByDayReq) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *GetPushDataByDayReq) GetUnixSecond() int64 {
	if x != nil {
		return x.UnixSecond
	}
	return 0
}

type GetPushDataByDayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date    string       `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Statics *BaseStatics `protobuf:"bytes,2,opt,name=statics,proto3" json:"statics,omitempty"`
}

func (x *GetPushDataByDayResp) Reset() {
	*x = GetPushDataByDayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPushDataByDayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushDataByDayResp) ProtoMessage() {}

func (x *GetPushDataByDayResp) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushDataByDayResp.ProtoReflect.Descriptor instead.
func (*GetPushDataByDayResp) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{9}
}

func (x *GetPushDataByDayResp) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetPushDataByDayResp) GetStatics() *BaseStatics {
	if x != nil {
		return x.Statics
	}
	return nil
}

type GetUserDataByDayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushAgent  string `protobuf:"bytes,1,opt,name=push_agent,json=pushAgent,proto3" json:"push_agent,omitempty"`
	BundleId   string `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	UnixSecond int64  `protobuf:"varint,3,opt,name=unix_second,json=unixSecond,proto3" json:"unix_second,omitempty"`
}

func (x *GetUserDataByDayReq) Reset() {
	*x = GetUserDataByDayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDataByDayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataByDayReq) ProtoMessage() {}

func (x *GetUserDataByDayReq) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataByDayReq.ProtoReflect.Descriptor instead.
func (*GetUserDataByDayReq) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserDataByDayReq) GetPushAgent() string {
	if x != nil {
		return x.PushAgent
	}
	return ""
}

func (x *GetUserDataByDayReq) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *GetUserDataByDayReq) GetUnixSecond() int64 {
	if x != nil {
		return x.UnixSecond
	}
	return 0
}

type GetUserDataByDayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date         string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Accumulative int32  `protobuf:"varint,2,opt,name=accumulative,proto3" json:"accumulative,omitempty"`
	Register     int32  `protobuf:"varint,3,opt,name=register,proto3" json:"register,omitempty"`
	Active       int32  `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Online       int32  `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
}

func (x *GetUserDataByDayResp) Reset() {
	*x = GetUserDataByDayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDataByDayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataByDayResp) ProtoMessage() {}

func (x *GetUserDataByDayResp) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataByDayResp.ProtoReflect.Descriptor instead.
func (*GetUserDataByDayResp) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserDataByDayResp) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetUserDataByDayResp) GetAccumulative() int32 {
	if x != nil {
		return x.Accumulative
	}
	return 0
}

func (x *GetUserDataByDayResp) GetRegister() int32 {
	if x != nil {
		return x.Register
	}
	return 0
}

func (x *GetUserDataByDayResp) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *GetUserDataByDayResp) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

type GetOnlineUserBy24HReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushAgent  string `protobuf:"bytes,1,opt,name=push_agent,json=pushAgent,proto3" json:"push_agent,omitempty"`
	BundleId   string `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	UnixSecond int64  `protobuf:"varint,3,opt,name=unix_second,json=unixSecond,proto3" json:"unix_second,omitempty"`
}

func (x *GetOnlineUserBy24HReq) Reset() {
	*x = GetOnlineUserBy24HReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnlineUserBy24HReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUserBy24HReq) ProtoMessage() {}

func (x *GetOnlineUserBy24HReq) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUserBy24HReq.ProtoReflect.Descriptor instead.
func (*GetOnlineUserBy24HReq) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{12}
}

func (x *GetOnlineUserBy24HReq) GetPushAgent() string {
	if x != nil {
		return x.PushAgent
	}
	return ""
}

func (x *GetOnlineUserBy24HReq) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *GetOnlineUserBy24HReq) GetUnixSecond() int64 {
	if x != nil {
		return x.UnixSecond
	}
	return 0
}

type GetOnlineUserBy24HResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date       string                               `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	OnlineList []*GetOnlineUserBy24HResp_OnlineInfo `protobuf:"bytes,2,rep,name=online_list,json=onlineList,proto3" json:"online_list,omitempty"`
}

func (x *GetOnlineUserBy24HResp) Reset() {
	*x = GetOnlineUserBy24HResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnlineUserBy24HResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUserBy24HResp) ProtoMessage() {}

func (x *GetOnlineUserBy24HResp) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUserBy24HResp.ProtoReflect.Descriptor instead.
func (*GetOnlineUserBy24HResp) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{13}
}

func (x *GetOnlineUserBy24HResp) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetOnlineUserBy24HResp) GetOnlineList() []*GetOnlineUserBy24HResp_OnlineInfo {
	if x != nil {
		return x.OnlineList
	}
	return nil
}

type BaseStatics_Total struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target  int32 `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Receive int32 `protobuf:"varint,2,opt,name=receive,proto3" json:"receive,omitempty"`
	Display int32 `protobuf:"varint,3,opt,name=display,proto3" json:"display,omitempty"`
	Click   int32 `protobuf:"varint,4,opt,name=click,proto3" json:"click,omitempty"`
	Msg     int32 `protobuf:"varint,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BaseStatics_Total) Reset() {
	*x = BaseStatics_Total{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseStatics_Total) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseStatics_Total) ProtoMessage() {}

func (x *BaseStatics_Total) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseStatics_Total.ProtoReflect.Descriptor instead.
func (*BaseStatics_Total) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BaseStatics_Total) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *BaseStatics_Total) GetReceive() int32 {
	if x != nil {
		return x.Receive
	}
	return 0
}

func (x *BaseStatics_Total) GetDisplay() int32 {
	if x != nil {
		return x.Display
	}
	return 0
}

func (x *BaseStatics_Total) GetClick() int32 {
	if x != nil {
		return x.Click
	}
	return 0
}

func (x *BaseStatics_Total) GetMsg() int32 {
	if x != nil {
		return x.Msg
	}
	return 0
}

type BaseStatics_Detail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target       int32  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Receive      int32  `protobuf:"varint,2,opt,name=receive,proto3" json:"receive,omitempty"`
	Display      int32  `protobuf:"varint,3,opt,name=display,proto3" json:"display,omitempty"`
	Click        int32  `protobuf:"varint,4,opt,name=click,proto3" json:"click,omitempty"`
	Manufacturer string `protobuf:"bytes,5,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
}

func (x *BaseStatics_Detail) Reset() {
	*x = BaseStatics_Detail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseStatics_Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseStatics_Detail) ProtoMessage() {}

func (x *BaseStatics_Detail) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseStatics_Detail.ProtoReflect.Descriptor instead.
func (*BaseStatics_Detail) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0, 1}
}

func (x *BaseStatics_Detail) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *BaseStatics_Detail) GetReceive() int32 {
	if x != nil {
		return x.Receive
	}
	return 0
}

func (x *BaseStatics_Detail) GetDisplay() int32 {
	if x != nil {
		return x.Display
	}
	return 0
}

func (x *BaseStatics_Detail) GetClick() int32 {
	if x != nil {
		return x.Click
	}
	return 0
}

func (x *BaseStatics_Detail) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

type BaseStatics_Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BaseStatics_Action) Reset() {
	*x = BaseStatics_Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseStatics_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseStatics_Action) ProtoMessage() {}

func (x *BaseStatics_Action) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseStatics_Action.ProtoReflect.Descriptor instead.
func (*BaseStatics_Action) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0, 2}
}

func (x *BaseStatics_Action) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BaseStatics_Action) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetOnlineUserBy24HResp_OnlineInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixMillisecond int64 `protobuf:"varint,1,opt,name=unix_millisecond,json=unixMillisecond,proto3" json:"unix_millisecond,omitempty"`
	Online          int32 `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
}

func (x *GetOnlineUserBy24HResp_OnlineInfo) Reset() {
	*x = GetOnlineUserBy24HResp_OnlineInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnlineUserBy24HResp_OnlineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUserBy24HResp_OnlineInfo) ProtoMessage() {}

func (x *GetOnlineUserBy24HResp_OnlineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUserBy24HResp_OnlineInfo.ProtoReflect.Descriptor instead.
func (*GetOnlineUserBy24HResp_OnlineInfo) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetOnlineUserBy24HResp_OnlineInfo) GetUnixMillisecond() int64 {
	if x != nil {
		return x.UnixMillisecond
	}
	return 0
}

func (x *GetOnlineUserBy24HResp_OnlineInfo) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

var File_stats_proto protoreflect.FileDescriptor

var file_stats_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x50,
	0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x84, 0x04, 0x0a, 0x0b, 0x42, 0x61,
	0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63,
	0x73, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3f,
	0x0a, 0x0b, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x0a, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x3f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x1a, 0x7b, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x8e, 0x01,
	0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61,
	0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x1a, 0x30,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0xca, 0x01, 0x0a, 0x0d, 0x42, 0x61, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x75, 0x73, 0x68, 0x4e, 0x75,
	0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x75, 0x6d,
	0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x66, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x75, 0x73, 0x68, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x75, 0x73, 0x68, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x67, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63,
	0x73, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x63,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x73, 0x68, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x22, 0x5b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x31, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73,
	0x22, 0x6e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x73, 0x68, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x78, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x22, 0x4c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x72,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x44,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x73, 0x68, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x78, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x22, 0x5d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x79, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x31,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63,
	0x73, 0x22, 0x72, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x79, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x73, 0x68,
	0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75,
	0x73, 0x68, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x78, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x22, 0x74, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x32, 0x34, 0x48, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x75, 0x73, 0x68, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x75, 0x73, 0x68, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x78, 0x5f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x6e,
	0x69, 0x78, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0xcd, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x32, 0x34, 0x48, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x6f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x32, 0x34, 0x48, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x4f, 0x0a, 0x0a, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29, 0x0a, 0x10, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x69,
	0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0f, 0x75, 0x6e, 0x69, 0x78, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x32, 0xf3, 0x03, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x17,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x1b, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x1a, 0x1c, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1b, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75,
	0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x57, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x44, 0x61,
	0x79, 0x12, 0x1f, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x44, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x1a, 0x20, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x44, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x44, 0x61, 0x79, 0x12, 0x1f, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x42, 0x79, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x50, 0x75,
	0x73, 0x68, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x5d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x79, 0x32, 0x34, 0x48, 0x12, 0x21, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x79, 0x32, 0x34, 0x48, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x32, 0x34, 0x48, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData = file_stats_proto_rawDesc
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_stats_proto_rawDescData)
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_stats_proto_goTypes = []interface{}{
	(*BaseStatics)(nil),                       // 0: Push.Stats.BaseStatics
	(*BasePushCount)(nil),                     // 1: Push.Stats.BasePushCount
	(*GetTasksReq)(nil),                       // 2: Push.Stats.GetTasksReq
	(*GetTasksResp)(nil),                      // 3: Push.Stats.GetTasksResp
	(*GetTaskGroupReq)(nil),                   // 4: Push.Stats.GetTaskGroupReq
	(*GetTaskGroupResp)(nil),                  // 5: Push.Stats.GetTaskGroupResp
	(*GetPushCountReq)(nil),                   // 6: Push.Stats.GetPushCountReq
	(*GetPushCountResp)(nil),                  // 7: Push.Stats.GetPushCountResp
	(*GetPushDataByDayReq)(nil),               // 8: Push.Stats.GetPushDataByDayReq
	(*GetPushDataByDayResp)(nil),              // 9: Push.Stats.GetPushDataByDayResp
	(*GetUserDataByDayReq)(nil),               // 10: Push.Stats.GetUserDataByDayReq
	(*GetUserDataByDayResp)(nil),              // 11: Push.Stats.GetUserDataByDayResp
	(*GetOnlineUserBy24HReq)(nil),             // 12: Push.Stats.GetOnlineUserBy24HReq
	(*GetOnlineUserBy24HResp)(nil),            // 13: Push.Stats.GetOnlineUserBy24HResp
	(*BaseStatics_Total)(nil),                 // 14: Push.Stats.BaseStatics.Total
	(*BaseStatics_Detail)(nil),                // 15: Push.Stats.BaseStatics.Detail
	(*BaseStatics_Action)(nil),                // 16: Push.Stats.BaseStatics.Action
	(*GetOnlineUserBy24HResp_OnlineInfo)(nil), // 17: Push.Stats.GetOnlineUserBy24HResp.OnlineInfo
}
var file_stats_proto_depIdxs = []int32{
	14, // 0: Push.Stats.BaseStatics.total:type_name -> Push.Stats.BaseStatics.Total
	15, // 1: Push.Stats.BaseStatics.detail_list:type_name -> Push.Stats.BaseStatics.Detail
	16, // 2: Push.Stats.BaseStatics.action_list:type_name -> Push.Stats.BaseStatics.Action
	0,  // 3: Push.Stats.GetTasksResp.statics_list:type_name -> Push.Stats.BaseStatics
	0,  // 4: Push.Stats.GetTaskGroupResp.statics:type_name -> Push.Stats.BaseStatics
	1,  // 5: Push.Stats.GetPushCountResp.count_list:type_name -> Push.Stats.BasePushCount
	0,  // 6: Push.Stats.GetPushDataByDayResp.statics:type_name -> Push.Stats.BaseStatics
	17, // 7: Push.Stats.GetOnlineUserBy24HResp.online_list:type_name -> Push.Stats.GetOnlineUserBy24HResp.OnlineInfo
	2,  // 8: Push.Stats.Stats.GetTasks:input_type -> Push.Stats.GetTasksReq
	4,  // 9: Push.Stats.Stats.GetTaskGroup:input_type -> Push.Stats.GetTaskGroupReq
	6,  // 10: Push.Stats.Stats.GetPushCount:input_type -> Push.Stats.GetPushCountReq
	8,  // 11: Push.Stats.Stats.GetPushDataByDay:input_type -> Push.Stats.GetPushDataByDayReq
	10, // 12: Push.Stats.Stats.GetUserDataByDay:input_type -> Push.Stats.GetUserDataByDayReq
	12, // 13: Push.Stats.Stats.GetOnlineUserBy24H:input_type -> Push.Stats.GetOnlineUserBy24HReq
	3,  // 14: Push.Stats.Stats.GetTasks:output_type -> Push.Stats.GetTasksResp
	5,  // 15: Push.Stats.Stats.GetTaskGroup:output_type -> Push.Stats.GetTaskGroupResp
	7,  // 16: Push.Stats.Stats.GetPushCount:output_type -> Push.Stats.GetPushCountResp
	9,  // 17: Push.Stats.Stats.GetPushDataByDay:output_type -> Push.Stats.GetPushDataByDayResp
	11, // 18: Push.Stats.Stats.GetUserDataByDay:output_type -> Push.Stats.GetUserDataByDayResp
	13, // 19: Push.Stats.Stats.GetOnlineUserBy24H:output_type -> Push.Stats.GetOnlineUserBy24HResp
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseStatics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasePushCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTasksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTasksResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPushCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPushCountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPushDataByDayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPushDataByDayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDataByDayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDataByDayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnlineUserBy24HReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnlineUserBy24HResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseStatics_Total); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseStatics_Detail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseStatics_Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnlineUserBy24HResp_OnlineInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_rawDesc = nil
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StatsClient is the client API for Stats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsClient interface {
	GetTasks(ctx context.Context, in *GetTasksReq, opts ...grpc.CallOption) (*GetTasksResp, error)
	GetTaskGroup(ctx context.Context, in *GetTaskGroupReq, opts ...grpc.CallOption) (*GetTaskGroupResp, error)
	GetPushCount(ctx context.Context, in *GetPushCountReq, opts ...grpc.CallOption) (*GetPushCountResp, error)
	GetPushDataByDay(ctx context.Context, in *GetPushDataByDayReq, opts ...grpc.CallOption) (*GetPushDataByDayResp, error)
	GetUserDataByDay(ctx context.Context, in *GetUserDataByDayReq, opts ...grpc.CallOption) (*GetUserDataByDayResp, error)
	GetOnlineUserBy24H(ctx context.Context, in *GetOnlineUserBy24HReq, opts ...grpc.CallOption) (*GetOnlineUserBy24HResp, error)
}

type statsClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsClient(cc grpc.ClientConnInterface) StatsClient {
	return &statsClient{cc}
}

func (c *statsClient) GetTasks(ctx context.Context, in *GetTasksReq, opts ...grpc.CallOption) (*GetTasksResp, error) {
	out := new(GetTasksResp)
	err := c.cc.Invoke(ctx, "/Push.Stats.Stats/GetTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetTaskGroup(ctx context.Context, in *GetTaskGroupReq, opts ...grpc.CallOption) (*GetTaskGroupResp, error) {
	out := new(GetTaskGroupResp)
	err := c.cc.Invoke(ctx, "/Push.Stats.Stats/GetTaskGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetPushCount(ctx context.Context, in *GetPushCountReq, opts ...grpc.CallOption) (*GetPushCountResp, error) {
	out := new(GetPushCountResp)
	err := c.cc.Invoke(ctx, "/Push.Stats.Stats/GetPushCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetPushDataByDay(ctx context.Context, in *GetPushDataByDayReq, opts ...grpc.CallOption) (*GetPushDataByDayResp, error) {
	out := new(GetPushDataByDayResp)
	err := c.cc.Invoke(ctx, "/Push.Stats.Stats/GetPushDataByDay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetUserDataByDay(ctx context.Context, in *GetUserDataByDayReq, opts ...grpc.CallOption) (*GetUserDataByDayResp, error) {
	out := new(GetUserDataByDayResp)
	err := c.cc.Invoke(ctx, "/Push.Stats.Stats/GetUserDataByDay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetOnlineUserBy24H(ctx context.Context, in *GetOnlineUserBy24HReq, opts ...grpc.CallOption) (*GetOnlineUserBy24HResp, error) {
	out := new(GetOnlineUserBy24HResp)
	err := c.cc.Invoke(ctx, "/Push.Stats.Stats/GetOnlineUserBy24H", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServer is the server API for Stats service.
type StatsServer interface {
	GetTasks(context.Context, *GetTasksReq) (*GetTasksResp, error)
	GetTaskGroup(context.Context, *GetTaskGroupReq) (*GetTaskGroupResp, error)
	GetPushCount(context.Context, *GetPushCountReq) (*GetPushCountResp, error)
	GetPushDataByDay(context.Context, *GetPushDataByDayReq) (*GetPushDataByDayResp, error)
	GetUserDataByDay(context.Context, *GetUserDataByDayReq) (*GetUserDataByDayResp, error)
	GetOnlineUserBy24H(context.Context, *GetOnlineUserBy24HReq) (*GetOnlineUserBy24HResp, error)
}

// UnimplementedStatsServer can be embedded to have forward compatible implementations.
type UnimplementedStatsServer struct {
}

func (*UnimplementedStatsServer) GetTasks(context.Context, *GetTasksReq) (*GetTasksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (*UnimplementedStatsServer) GetTaskGroup(context.Context, *GetTaskGroupReq) (*GetTaskGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskGroup not implemented")
}
func (*UnimplementedStatsServer) GetPushCount(context.Context, *GetPushCountReq) (*GetPushCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPushCount not implemented")
}
func (*UnimplementedStatsServer) GetPushDataByDay(context.Context, *GetPushDataByDayReq) (*GetPushDataByDayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPushDataByDay not implemented")
}
func (*UnimplementedStatsServer) GetUserDataByDay(context.Context, *GetUserDataByDayReq) (*GetUserDataByDayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDataByDay not implemented")
}
func (*UnimplementedStatsServer) GetOnlineUserBy24H(context.Context, *GetOnlineUserBy24HReq) (*GetOnlineUserBy24HResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnlineUserBy24H not implemented")
}

func RegisterStatsServer(s *grpc.Server, srv StatsServer) {
	s.RegisterService(&_Stats_serviceDesc, srv)
}

func _Stats_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Push.Stats.Stats/GetTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetTasks(ctx, req.(*GetTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetTaskGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetTaskGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Push.Stats.Stats/GetTaskGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetTaskGroup(ctx, req.(*GetTaskGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetPushCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPushCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetPushCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Push.Stats.Stats/GetPushCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetPushCount(ctx, req.(*GetPushCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetPushDataByDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPushDataByDayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetPushDataByDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Push.Stats.Stats/GetPushDataByDay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetPushDataByDay(ctx, req.(*GetPushDataByDayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetUserDataByDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDataByDayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetUserDataByDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Push.Stats.Stats/GetUserDataByDay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetUserDataByDay(ctx, req.(*GetUserDataByDayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetOnlineUserBy24H_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineUserBy24HReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetOnlineUserBy24H(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Push.Stats.Stats/GetOnlineUserBy24H",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetOnlineUserBy24H(ctx, req.(*GetOnlineUserBy24HReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Push.Stats.Stats",
	HandlerType: (*StatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTasks",
			Handler:    _Stats_GetTasks_Handler,
		},
		{
			MethodName: "GetTaskGroup",
			Handler:    _Stats_GetTaskGroup_Handler,
		},
		{
			MethodName: "GetPushCount",
			Handler:    _Stats_GetPushCount_Handler,
		},
		{
			MethodName: "GetPushDataByDay",
			Handler:    _Stats_GetPushDataByDay_Handler,
		},
		{
			MethodName: "GetUserDataByDay",
			Handler:    _Stats_GetUserDataByDay_Handler,
		},
		{
			MethodName: "GetOnlineUserBy24H",
			Handler:    _Stats_GetOnlineUserBy24H_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}
